var petDog = "Rex";
var petCat = "Pepper";
console.log("My pet dog's name is:", petDog);
console.log("My oet cat's name is:", petCat);
var catSound = "purr";
var dogSound = "woof";
console.log(petDog, "says", dogSound);
console.log(petCat, "says", catSound);
catSound="meow";
console.log(petCat, "Now says", catSound);
var square = 4**2;
console.log(square);